[package]
name = "buf-yaml"
version = "0.2.0"
edition = "2021"

[dependencies]
tonic = "0.13"
tokio = {version = "1.40.0", features = ["full"]}
prost = "0.13.3"

[build-dependencies]
tonic-buf-build = {path = "../../"}
tonic-build = "*"
